DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
#    SAMPLER: "DistributedSampler"
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8
  K_TRANSFORMS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "randaugment2", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  CHECKPOINT_FREQ: 1
  PRINT_FREQ: 100

TEST:
  NO_TEST: True
  PER_CLASS_RESULT: True

MODEL:
  BACKBONE:
    NAME: "RN50"
